version: "2"
run:
  tests: false
linters:
  enable:
    - revive
    - staticcheck
    - gosimple
    - unused
  disable:
    - dupl
    - staticcheck
output:
  formats:
    text:
      path: stdout
      color: true
issues:
  exclude:
    - "runTestCases.*unused"
    - "svc.BatchAccountImport.*not checked"
    - "ALL_CAPS"
